<?php

/**
 * @file
 * Defines hook implementations for the Matthew module.
 */

/**
 * Implements hook_theme().
 */
function matthew_theme(array $existing, string $type, string $theme, string $path): array {
  $extensionPathResolver = Drupal::service('extension.path.resolver');
  $path = $extensionPathResolver->getPath('module', 'matthew') . '/templates';

  return [
    'cats' => [
      'variables' => [
        'content' => NULL,
        'form' => [],
      ],
      'template' => 'cats',
      'path' => $path,
    ],
    'cats-view' => [
      'variables' => [
        'content' => NULL,
        'rows' => [],
      ],
      'template' => 'cats-view',
      'path' => $path,
    ],
    'matthew-admin-cats' => [
      'variables' => [
        'content' => NULL,
        'rows' => [],
      ],
      'template' => 'matthew-admin-cats',
      'path' => $path,
    ],
  ];
}
