<?php

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function matthew_theme($existing, $type, $theme, $path) {
  $extensionPathResolver = \Drupal::service('extension.path.resolver');
  return [
    'cats' => [
      'variables' => [
        'content' => NULL,
        'form' => [],
      ],
      'template' => 'cats',
      'path' => $extensionPathResolver->getPath('module', 'matthew') . '/templates',
    ],
    'cats-view' => [
      'variables' => [
        'content' => NULL,
        'rows' => []
      ],
      'template' => 'cats-view',
      'path' => $extensionPathResolver->getPath('module', 'matthew') . '/templates',
    ],
  ];
}

/**
 * Implements hook_page_attachments().
 */
function matthew_page_attachments(array &$attachments) {
  $route_name = \Drupal::routeMatch()->getRouteName();
  if ($route_name == 'matthew.view') {
    $attachments['#attached']['library'][] = 'matthew/cat-view-styles';
  }
}
