<?php

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function matthew_theme($existing, $type, $theme, $path) {
  $extensionPathResolver = \Drupal::service('extension.path.resolver');
  return [
    'cats' => [
      'variables' => [
        'content' => NULL,
        'form' => [],
      ],
      'template' => 'cats',
      'path' => $extensionPathResolver->getPath('module', 'matthew') . '/templates',
    ],
    'cats-view' => [
      'variables' => [
        'content' => NULL,
      ],
      'template' => 'cats-view',
      'path' => $extensionPathResolver->getPath('module', 'matthew') . '/templates',
    ],
  ];
}
